---
driver:
  name: vagrant

provisioner:
  name: shell

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-12.04
    driver:
      box: ubuntu/precise64

  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64

suites:
  - name: default
