---
<% kitchen_driver = ENV.fetch('KITCHEN_DRIVER', 'vagrant') %>

driver:
  name: <%= kitchen_driver %>

provisioner:
  name: shell
  data_path: provision/data

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-12.04
    driver:
    <% if kitchen_driver == "scaleway" %>
      image: 7258ac9b-61e7-4f69-a72d-b424de25fe84
    <% end %>
    <% if kitchen_driver == 'vagrant' %>
      box: ubuntu/precise64
    <% end %>

    provisioner:
      script: provision/ubuntu-12.04-bootstrap.sh

  - name: ubuntu-14.04
    driver:
    <% if kitchen_driver == "scaleway" %>
      image: 857de28c-39ce-4b15-9389-b68d8bb1bb51
    <% end %>
    <% if kitchen_driver == 'vagrant' %>
      box: ubuntu/trusty64
    <% end %>

    provisioner:
      script: provision/ubuntu-14.04-bootstrap.sh

suites:
  - name: default
