---
<% kitchen_driver = ENV.fetch('KITCHEN_DRIVER', 'vagrant') %>

driver:
  name: <%= kitchen_driver %>

<% if kitchen_driver == 'ec2' %>
driver_config:
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  security_group_ids:
    - <%= ENV['AWS_SECURITY_GROUP_ID'] %>

transport:
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
<% end %>

provisioner:
  name: shell
  data_path: provision/data

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-12.04
    driver:
    <% if kitchen_driver == 'vagrant' %>
      box: ubuntu/precise64
    <% end %>

    provisioner:
      script: provision/ubuntu-12.04-bootstrap.sh

  - name: ubuntu-14.04
    driver:
    <% if kitchen_driver == 'ec2' %>
      image_id: ami-3907d64e

    transport:
      username: ubuntu
    <% else %>
      box: ubuntu/trusty64
    <% end %>

    provisioner:
      script: provision/ubuntu-14.04-bootstrap.sh

suites:
  - name: default
