---
driver:
  name: vagrant

provisioner:
  name: shell
  data_path: provision/data

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-12.04
    driver:
      box: ubuntu/precise64
    provisioner:
      script: provision/ubuntu-12.04-bootstrap.sh

  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
    provisioner:
      script: provision/ubuntu-14.04-bootstrap.sh

suites:
  - name: default
