language: python

before_install:
  - . .test-env.sh
  - sudo apt-get update
  - sudo apt-get install "${TEST_AN_INSTALLED_PACKAGE_NAME}=${TEST_AN_INSTALLED_PACKAGE_VERSION}"
  - sudo apt-get remove $TEST_AN_UNINSTALLED_PACKAGE

install:
  - python setup.py sdist
  - pip install dist/`python setup.py --name`-`python setup.py --version`.tar.gz
  - pip install --upgrade -r test-requirements.txt

script:
  - . .test-env.sh
  - mamba
