language: ruby

rvm:
  - 2.4

install:
  - bundle install
  - sudo pip install awscli

script:
  - AWS_SSH_KEY_ID=$AWS_SSH_KEY_ID-$TRAVIS_JOB_NUMBER bundle exec make ec2_test

after_script:
  - AWS_SSH_KEY_ID=$AWS_SSH_KEY_ID-$TRAVIS_JOB_NUMBER bundle exec make ec2_destroy

env:
  matrix:
    - KITCHEN_INSTANCE=ubuntu-1204
    - KITCHEN_INSTANCE=ubuntu-1404
