language: ruby

rvm:
  - 2.4

before_install:
  - openssl aes-256-cbc -K $encrypted_442239fa91ec_key -iv $encrypted_442239fa91ec_iv -in scaleway_rsa.enc -out /tmp/scaleway_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/scaleway_rsa
  - ssh-add /tmp/scaleway_rsa

install:
  - bundle install

script:
  - bundle exec make scaleway_test

after_script:
  - bundle exec make scaleway_destroy

env:
  matrix:
  - KITCHEN_INSTANCE=ubuntu-1204
  - KITCHEN_INSTANCE=ubuntu-1404
